packages:
  - apps/*
  - packages/*

catalog:
  "@wisemen/eslint-config-vue": "^1.0.0-next.1"
  "eslint": "^9.22.0"
  "typescript": "5.8.2"
  "vitest": "3.0.8"
  "zod": "3.24.2"
  "@payloadcms/db-postgres": "3.28.1"
  "@payloadcms/next": "3.28.1"
  "@payloadcms/plugin-seo": "^3.28.1"
  "@payloadcms/richtext-lexical": "3.28.1"
  "@payloadcms/storage-s3": "3.28.1"
  "@payloadcms/ui": "3.28.1"
  "payload": "3.28.1"
  "@payloadcms/plugin-multi-tenant": "3.28.1"
