packages:
  - apps/*
  - packages/*

catalog:
  "@wisemen/eslint-config-vue": "^1.0.0-next.0"
  "eslint": "^9.20.1"
  "typescript": "5.7.3"
  "vitest": "3.0.5"
  "zod": "3.24.2"
  "@payloadcms/db-mongodb": "3.23.0"
  "@payloadcms/db-postgres": "3.23.0"
  "@payloadcms/next": "3.23.0"
  "@payloadcms/plugin-search": "3.23.0"
  "@payloadcms/plugin-seo": "^3.23.0"
  "@payloadcms/richtext-lexical": "3.23.0"
  "@payloadcms/richtext-slate": "3.23.0"
  "@payloadcms/storage-s3": "3.23.0"
  "@payloadcms/ui": "3.23.0"
  "payload": "3.23.0"
